baseurl = "https://resulumit.com/"
title = "Resul Umit"
author = "Resul Umit"
canonifyurls = true
relativeurls = false
paginate = 10
theme = "resulumit"
DisqusShortname = "researchtips"
#googleAnalytics = "G-GC34XXL0WV"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
pluralizeListTitles = false
buildFuture = true
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true

[params]

# Date format (refer to Go's date format: http://flippinggodateformat.com)
date_format = "2 January 2006"

# Number of posts to show on main page.
posts_count = 2

# Number of publications to show on main page.
pubs_count = 3

# Number of posts to show on main page.
unpublished_count = 2

# options for highlight.js (version, additional languages, and theme)
highlightjsVersion = "9.11.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"

[[params.social]]
icon = "fa-building-columns"
icon_pack = "fa-solid"
link = "https://www.durham.ac.uk/"
text = "School of Government and International Affairs, Durham University, Elvet Hill Road, Durham DH1 3TU, UK"

[[params.social]]
icon = "fa-envelope"
icon_pack = "fa-solid"
link = "mailto:resul.umit@durham.ac.uk"
text = "resul.umit@durham.ac.uk"

[[params.social]]
icon = "fa-bluesky"
icon_pack = "fa-brands"
link = "https://bsky.app/profile/resulumit.bsky.social"
text = "resulumit.bsky.social"
site = "Bluesky"

[[params.social]]
icon = "fa-github"
icon_pack = "fa-brands"
link = "https://github.com/resulumit"
text = "resulumit"
site = "GitHub"

[[params.social]]
icon = "fa-google-scholar"
icon_pack = "fa-brands"
link = "https://scholar.google.com/citations?user=J5Ck-vkAAAAJ&hl=en"
text = "Google Scholar"

# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 1

[[menu.main]]
name = "Unpublished"
url = "/unpublished/"
weight = 2

[[menu.main]]
name = "Teaching"
url = "/teaching/"
weight = 3

[[menu.main]]
name = "Supervision"
url = "/supervision/"
weight = 4

[[menu.main]]
name = "Data"
url = "/data/"
weight = 5

[[menu.main]]
name = "Outreach"
url = "/outreach/" 
weight = 6

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 7

[[menu.main]]
name = "About"
url = "/about/"
weight = 8