---
date: 2020-04-30
slug: rmd-workshop
title: "R Markdown workshop"
output: html_document
categories:
        - teaching
        - workshop
        - rstats
---

**Click <a href="https://resulumit.com/teaching/rmd_workshop.html" target="_blank"><b>here</b></a> for the slides, and <a href="https://github.com/resulumit/rmd_workshop" target="_blank"><b>here</b></a> for all the workshop materials.**

R Markdown has been at the centre of my research workflow for some time. It allows me to tidy and analyse data, create tables and figures, manage citations and references, and write up the results in one screen. 

And if, say, a regression table needs a new model, it often takes only a few lines of code and a click to reproduce the output --- be it a PDF, HTML, and/or a Word document.

In March 2020, I organised a full-day workshop at <a href="https://www.campus-luzern.ch/" target="_blank"><b>Campus Luzern</b></a>, to share my experience with researchers from the three universities in the Swiss Canton of Lucerne. It went very well.

Since then I have revised the workshop material, which you can find on <a href="https://github.com/resulumit/rmd_workshop" target="_blank">GitHub</a>. The slides are better viewed <a href="https://resulumit.com/teaching/rmd_workshop.html" target="_blank">here on my website</a>.&#42;

I would be happy to organise this workshop again. <a href="mailto:resuluy@uio.no?subject=R Markdown workshop">Let me know</a> if this might be possible at your institution.

And if you like the sound of this course, you might also be interested in the other digital-skills courses that I teach. Have a look at the [teaching section](https://resulumit.com/teaching/) of my website.

_____
&#42; These HTML slides crash for some Safari users. If using a different browser application, such as Chrome or Firefox, is not an option for you, I recommend viewing the <a href="https://github.com/resulumit/rmd_workshop/blob/master/presentation/rmd_workshop.pdf">PDF version of the slides</a> on GitHub.